### PR TITLE
Modernize Python 2 code to prepare for Python 3

### LINKED ISSUE #4: print() is a function in Python 3
flake8 testing of https://github.com/google/compare_gan on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./compare_gan/src/datasets.py:86:16: F821 undefined name 'xrange'
      for i in xrange(range_start, range_end)
               ^
./compare_gan/src/gan_lib.py:198:38: E999 SyntaxError: invalid syntax
        print " [*] Training started!"
                                     ^
./compare_gan/src/image_similarity.py:296:14: F821 undefined name 'xrange'
    for k in xrange(len(power_factors)):
             ^
./compare_gan/src/simple_task_pb2.py:46:46: F821 undefined name 'unicode'
      has_default_value=False, default_value=unicode("", "utf-8"),
                                             ^
./compare_gan/src/simple_task_pb2.py:53:46: F821 undefined name 'unicode'
      has_default_value=False, default_value=unicode("", "utf-8"),
                                             ^
./compare_gan/src/gans/WGAN.py:42:35: E999 SyntaxError: invalid syntax
      print "Using Adam optimizer."
                                  ^
./compare_gan/src/gans/gans_with_penalty.py:73:35: E999 SyntaxError: invalid syntax
      print "Using Adam optimizer."
                                  ^
./compare_gan/src/gans/ops.py:141:35: E999 SyntaxError: invalid syntax
  print " [*] Spectral norm layers"
                                  ^
4     E999 SyntaxError: invalid syntax
4     F821 undefined name 'xrange'
8
```

### PR DESCRIPTION
**Pull request by cclauss**
Fixes #4 

* __print()__ is a function in Python 3.
* __unicode()__ was removed in Python 3 because all __str__ are Unicode.
* __xrange()__ was removed in Python 3 in favor of __range()__.

### CODE REVIEW

**Comment by cyfra** [comment]
Thanks for the PR.

For xrange: could you simply replace the xrange with range inside the code (instead of doing the try/except replacement).

**Comment by cclauss** [comment]
There is a Python 2 memory and performance penalty to pay for doing that.  If you are OK with that then I can go ahead.

**Comment by cyfra** [comment]
Yes, please go ahead.

**Comment by cyfra** [comment]
Yes, please go ahead.

**Comment by Marvin182** [comment]
We could use `from six.moves import range` as recommended by the [TF Style Guide](https://www.tensorflow.org/community/style_guide)? This avoids the memory/performance penalty in Python 2.

**Comment by cclauss** [comment]
An even better solution is possible because [this project depends on __future__](https://github.com/google/compare_gan/blob/master/setup.py#L40), we can [__from builtins import range__](http://python-future.org/reference.html?highlight=range#module-future.types) and change all instances of __xrange()__ to __range()__.

**Pull request merged**
